//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace massey_effect_matthews_mages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUser
    {
        public LogUser()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}
