//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace massey_effect_matthews_mages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserName { get; set; }
        public int CurrentHealth { get; set; }
        public int MonstersKilled { get; set; }
        public int RoomsTraveled { get; set; }
        public int Attack { get; set; }
        public int Defense { get; set; }
        public int AttackSpeed { get; set; }
        public int AttackRange { get; set; }
        public int MoveSpeed { get; set; }
        public int HighMonstersKilled { get; set; }
        public int HighRoomsTraveled { get; set; }
        public int HighAttack { get; set; }
        public int HighDefense { get; set; }
    }
}
